Repository luisgaboardi/Forum-TutorBrasil, pull requests merged in 2021-08, with the labels that each got.

#6 Create repo templates
  .github/ISSUE_TEMPLATE/template-generico-de-issues.md
  .github/pull_request_template.md
Labels: documentation

#19 10-low-fidelity-prototype
  docs/images/prot 1.jpeg
  docs/images/prot 2.jpeg
  docs/images/prot 3.jpeg
  docs/images/prot 4.jpeg
Labels: documentation, prototype

#20 Adição das Personas
  .gitignore
  docs/images/personas/alexandre.png
  docs/images/personas/caio.png
  docs/images/personas/maria.png
  docs/project/personas.md
  mkdocs.yml
Labels: documentation

#22 Fix image size in communication plan
  docs/management/communication-plan.md
Labels: documentation

#23 Documentação do Protótipo de Baixa Fidelidade
  docs/assets/low-prototype/low-prototype-01.jpeg
  docs/assets/low-prototype/low-prototype-02.jpeg
  docs/assets/low-prototype/low-prototype-03.jpeg
  docs/assets/low-prototype/low-prototype-04.jpeg
  docs/project/low-prototype.md
Labels: documentation, prototype

#24 Merge dev to main for first release and second presentation
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/workflows/ci.yml
  .gitignore
  README.md
  docs/assets/low-prototype/low-prototype-01.jpeg
  docs/assets/low-prototype/low-prototype-02.jpeg
  docs/assets/low-prototype/low-prototype-03.jpeg
  docs/assets/low-prototype/low-prototype-04.jpeg
  docs/assets/personas/alexandre.png
  docs/assets/personas/caio.png
  docs/assets/personas/maria.png
  docs/assets/releases/release-1/release-1-01.jpg
  docs/assets/releases/release-1/release-1-02.jpg
  docs/assets/releases/release-1/release-1-03.jpg
  docs/assets/releases/release-1/release-1-04.jpg
  docs/assets/releases/release-1/release-1-05.jpg
  docs/assets/releases/release-1/release-1-06.jpg
  docs/assets/releases/release-1/release-1-07.jpg
  docs/assets/releases/release-1/release-1-08.jpg
  docs/assets/releases/release-1/release-1-09.jpg
  docs/assets/releases/release-1/release-1-10.jpg
  docs/assets/releases/release-1/release-1-11.jpg
  docs/assets/releases/release-1/release-1-12.jpg
  docs/assets/releases/release-1/release-1-13.jpg
  docs/assets/tools/drive.png
  docs/assets/tools/figma.png
  docs/assets/tools/github.png
  docs/assets/tools/teams.png
  docs/assets/tools/telegram.png
  docs/index.md
  docs/management/communication-plan.md
  docs/management/methodology-plan.md
  docs/management/product-roadmap.md
  docs/project/CODE_OF_CONDUCT.md
  docs/project/CONTRIBUTING.md
  docs/project/forms/first.md
  docs/project/high-prototype.md
  docs/project/low-prototype.md
  docs/project/mid-prototype.md
  docs/project/personas.md
  docs/project/product-backlog.md
  docs/releases/release-1.md
  mkdocs.yml
  requirements.txt
Labels: documentation, survey, prototype
